server:
  port: 9091

logging:
  level:
    org:
      springframework:
        web: INFO

spring:
  datasource:
    url: jdbc:mariadb://quarmaldb.cal7gn03b1oe.ap-northeast-2.rds.amazonaws.com:3306/test?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: org.mariadb.jdbc.Driver
    username: admin
    password: ljsCz0412
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher